[dotfiles]
"~/.bashrc" = {}
"~/.config/DankMaterialShell/plugin_settings.json" = {}
"~/.config/DankMaterialShell/settings.json" = {}
"~/.config/foot/foot.ini" = {}
"~/.config/ghostty/config" = {}
"~/.config/hypr/hyprland.lua" = {}
"~/.config/kitty/kitty.conf" = {}
"~/.config/mise/config.toml" = {}
"~/.config/mise/yay.sh" = {}
"~/.config/systemd/user/dms.service.d/override.conf" = {}
"~/.emacs" = {}
"~/.pi/agent/AGENTS.md" = {}
"~/.pi/agent/extensions" = {}
"~/.pi/agent/settings.json" = {}
"~/scripts" = {}



[bootstrap.packages]
"pacman:hyprland" = "latest"
"pacman:dms-shell" = "latest"
"pacman:quickshell" = "latest"
"pacman:ghostty" = "latest"
"pacman:greetd" = "latest"
"pacman:greetd-dms-greeter-bin" = "latest"
"pacman:greetd-dms-greeter-bin-debug" = "latest"
"pacman:matugen" = "latest"
"pacman:xdg-desktop-portal-gtk" = "latest"
"pacman:nvidia-open" = "latest"
"pacman:mise" = "latest"
"pacman:mesa-utils" = "latest"
"pacman:jq" = "latest"
"pacman:alacritty" = "latest"
"pacman:arduino-cli" = "latest"
"pacman:freecad" = "latest"
"pacman:dgop" = "latest"
"pacman:xorg-xhost" = "latest"
"pacman:vim" = "latest"
"pacman:gparted" = "latest"
"pacman:mc" = "latest"
"pacman:glxinfo" = "latest"
"pacman:telegram-desktop" = "latest"
"pacman:unrar" = "latest"
"pacman:wget" = "latest"
"pacman:net-tools" = "latest"
"pacman:rawtherapee" = "latest"
"pacman:gimp" = "latest"
"pacman:geeqie" = "latest"
"pacman:linux-headers" = "latest"
"pacman:linux-lts-headers" = "latest"
"pacman:flameshot" = "latest"
"pacman:syncthing" = "latest"
"pacman:pipewire-pulse" = "latest"
"pacman:pipewire-alsa" = "latest"
"pacman:fish" = "latest"
"pacman:ncdu" = "latest"
"pacman:vlc" = "latest"
"pacman:vlc-plugins-all" = "latest"
"pacman:kitty" = "latest"
"pacman:foot" = "latest"
"pacman:ffmpeg" = "latest"
"pacman:stellarium" = "latest"
"pacman:kstars" = "latest"
"pacman:prusa-slicer" = "latest"
"pacman:timeshift" = "latest"
"pacman:platformio-core" = "latest"
"pacman:github-cli" = "latest"
"pacman:ttf-jetbrains-mono-nerd" = "latest"
"pacman:fastfetch" = "latest"
"aur:google-chrome" = "latest"
"aur:visual-studio-code-bin" = "latest"
"aur:freecad-appimage" = "latest"
"aur:realvnc-vnc-viewer-7" = "latest"
"aur:auto-cpufreq" = "latest"
"aur:llama.cpp-cuda-git" = "latest"
"aur:zfs-dkms" = "latest"
"aur:zfs-utils" = "latest"
"aur:mergerfs" = "latest"

[tools]
pi = "latest"
oh-my-pi = "latest"
node = "latest"
bun = "latest"


[tasks.nvidia]
run="""
echo "options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/tmp" | sudo tee /etc/modprobe.d/nvidia-power-management.conf 
sudo systemctl enable --now nvidia-suspend.service
sudo systemctl enable --now nvidia-hibernate.service
sudo systemctl status nvidia-suspend.service
sudo systemctl status nvidia-hibernate.service
"""

[tasks.zfs]
run="""
sudo pacman -S --noconfirm --needed linux-headers
yay -S --noconfirm --needed zfs-dkms zfs-utils
sudo zpool import data1
sudo zpool set cachefile=/etc/zfs/zpool.cache data1
sudo systemctl enable --now zfs-scrub-weekly@zroot.timer
sudo systemctl enable --now zfs.target
sudo systemctl enable --now zfs-import.target
sudo systemctl enable --now zfs-import-cache
sudo systemctl enable --now zfs-mount
"""

[tasks.bootstrap]
run = """
sudo mkdir -p /ssd /data
systemctl --user restart pipewire
xhost +si:localuser:root
"""
